### ISSUE TITLE
classic mode without selected breaks plugin

### ISSUE THREAD

**Issue by thadmiller** [thdoan/pretty-dropdowns#10]
When classic property is true, applying the prettydropdown to a <select> that does not have an <option> with the selected attribute, the plugin renders an unusable empty box. It's easy to work around (for my situation anyway), but like the built in <select>, I think the plugin should default to selecting the first item if one is not selected - or, at minimum, at least allow the dropdown to function.

**Comment by thadmiller** [comment]
Actually... it's not an issue of not having an <option> with the selected attribute, the issue presents when the selected <option> (or first in the list, if none are selected) does not have a value. It's fairly common to have something like `<option value="">None</option>` or `<option value="">Select an option...</option>` but these don't work when the classic property is set to true.

**Comment by thdoan** [comment]
Thanks for reporting this. It has been fixed in v4.13.0.

**Comment by thadmiller** [comment]
Confirmed this works; thanks!
