### ISSUE TITLE
Setting width can default to min-width 100%

### ISSUE THREAD

**Issue by resih5** [thdoan/pretty-dropdowns#12]
I'm loving the plugin, simple and effective. I am using the 'width' parameter to manually set the width of wrapper  but for some reason jquery is calculating the width of the $items ('option' elements) to be 100% of the screen so it will set the width to the value given but then set the dropdown parent min-width to the calculated 100%.

ex. style='width:300px; min-width:1200px'

In v4.13.00 the code setting min-width in on line 145. It is not so a bug in the plugin but how jquery is determining the width of the 'option' elements. I changed my local copy to use same width as what I assign and it seems to work for me but I figure there is a reason why you are setting the min-width.

**Comment by thdoan** [comment]
In some cases, if line 145 is not there, then the widget can be rendered incorrectly. You can override this in CSS using `!important`.
