### ISSUE TITLE
Overflow in Bootstrap Modals

### ISSUE THREAD

**Issue by deltaGPhys** [thdoan/pretty-dropdowns#14]
No matter what I do, I can't get the dropdown to overflow the header/footer of a BS modal (without everything else overflowing too) - any guidance on that behavior?

**Comment by thdoan** [comment]
Try setting the menu's `z-index` to a super-high number like 9999 (or higher).

**Comment by deltaGPhys** [comment]
That didn't work either - sorry, didn't say that before.

**Comment by thdoan** [comment]
Do you mind putting up a sample page showing the issue?

**Comment by deltaGPhys** [comment]
Issue was resolved by setting the modal-body's overflow-y to visible (from auto).
