### ISSUE TITLE
Suggestion: classic functionality

### ISSUE THREAD

**Issue by mnervik** [thdoan/pretty-dropdowns#15]
**Nice to have**
- _Infinite timeout_: If you set hoverIntent to -1, the menu should never close. And yes I know that you could set it to some extreme high number to get the same result. But doing this instead might improve performance in those cases
- _Close menu on blur click_: If the dropdown is opened and you click on the background, it should close the dropdown

**Comment by thdoan** [comment]
Thanks for the suggestions! I'll close this when implemented.

**Comment by thdoan** [comment]
@mnervik this issue has been fixed in [v4.17.0](https://github.com/thdoan/pretty-dropdowns/releases/tag/v4.17.0). Please confirm and close. Thanks for reporting this.
