### ISSUE TITLE
Suggestion: Close button

### ISSUE THREAD

**Issue by OLSA** [thdoan/pretty-dropdowns#17]
Hello,
thanks for this nice plugin. 
Here is CSS addition which add "cross" or close icon when dropdown is active.
My problem was to **close dropdown** on iPhone 7 when I use it in **multiselect** mode (clicking outside does not close it).

![prettydropdown-close-button](https://user-images.githubusercontent.com/2437221/53775054-452b0b00-3ef1-11e9-8461-adfc6561c477.jpg)

```
/* css close icon addition */
.prettydropdown.arrow > ul.active > li.selected:before, 
.prettydropdown.arrow > ul.active > li.selected:after {
  position: absolute;
  top: 0px;
  right: 16px;  
  width: 16px;
  height: 16px;
  opacity: 1;  
  content: ' '; 
  width: 2px;  
}

.prettydropdown.arrow > ul.active > li.selected:before {
  transform: rotate(45deg);
}

.prettydropdown.arrow > ul.active > li.selected:after {
  transform: rotate(-45deg);
}

.prettydropdown.arrow > ul.active > li.selected:before, 
.prettydropdown.arrow > ul.active > li.selected:after,
.prettydropdown.arrow > ul.active > li.selected.hover:before, 
.prettydropdown.arrow > ul.active > li.selected.hover:after {  
  background-color: #fff;
}

.prettydropdown.arrow > ul.active > li.selected.nohover:before, 
.prettydropdown.arrow > ul.active > li.selected.nohover:after {  
  background-color: #777;
}
```

Regards.

**Comment by thdoan** [comment]
Thanks for this suggestion. When I fix issue #15 (second point), this should no longer be an issue. As I want to keep this plugin lightweight and customizable via CSS, I will not be implementing this and instead will move this to the Wiki.
