### ISSUE TITLE
placeholder title to keep for first option

### ISSUE THREAD

**Issue by lejardindeden** [thdoan/pretty-dropdowns#2]
Hi,

If I want to have a placeholder option to keep at first option, how can I do that ?

Thank you for help.

**Comment by thdoan** [comment]
That's currently not an option, but if you need something like that I can add it.

**Comment by thdoan** [comment]
UPDATE: As of [v4.8.0](https://github.com/thdoan/pretty-dropdowns/releases/tag/v4.8.0) you can now choose classic behavior (menu items don't rearrange upon selection) by setting the `classic` option to `true`, e.g.:

```
$('.pretty').prettyDropdown({
  classic: true
});
```

**Comment by lejardindeden** [comment]
Thank you ! :)
