### ISSUE TITLE
Bug : space char in option value leads to crash

### ISSUE THREAD

**Issue by badulesia** [thdoan/pretty-dropdowns#4]
Hello
This works
`<option value="twowords">Two words</option>`
That doesn't
`<option value="two words">Two words</option>`

Conclusion : an option value with a space char causes the script to fail.
In the code generated by the plugin, I can see data-value=two words, that of course cause the script to crash as there is no quote embedding "two words". Coders may want to use an option value with a space char inside.
I have also a script with option values such as <= or >= that crashes for the same reason, no quote embedding, so <= that is regarded as a test instead of a just a string.
I have quickly browse the code and the error maybe line 372 in the ternary test. But you know your code better of course :)

**Comment by thdoan** [comment]
Thanks for reporting this. I will fix this in the same release as your feature request :)

**Comment by badulesia** [comment]
Le 29/03/2017 à 05:41, Tom Doan a écrit :
> Thanks for reporting this. I will fix this in the same release as your
> feature request :)
>
Thank you :)

I'm using your plugin in a php project. I was using a previous one that 
is no longer maintained by its author. Hence I'm looking for a new one. 
I picked up yours from various ones as it seems the most effective. Its 
CSS is easily readable and modifiable.

**Comment by thdoan** [comment]
I was using Bootstrap-select before, but the most recent project didn't use Bootstrap and I couldn't find anything simple and lightweight, so had to roll my own.

**Comment by thdoan** [comment]
The fix will be in v4.9.0.
