### ISSUE TITLE
Suggestion : improve display for multiple select

### ISSUE THREAD

**Issue by badulesia** [thdoan/pretty-dropdowns#6]
Hello (again)
When used with the multiple attribute, the dropdown displays the list of selected options. But if too many options are selected, they can't all be displayed due to insufficient width. This is the expected behavior, nothing's wrong. With a large number of options, you can't really know what is selected.

What about instead displaying a message in that case ?
- when none selected : "none selected" or keep empty ?
- less than 3 selected : display their names (like actually)
- = or > 3 selected : display "3/8 selected" (for example with a total of 8 options)
I think this will be more clear to the user.
Thank you :)

**Comment by thdoan** [comment]
Right now there is a tooltip if you hover the mouse cursor over the drop-down. What do you think about that?

**Comment by badulesia** [comment]
Le 04/04/2017 à 13:19, Tom Doan a écrit :
> Right now there is a tooltip if you hover the mouse cursor over the
> drop-down. What do you think about that?
>
> —
Oups, I haven't noticed it yet.

I agree, but I still think that a custom message is usefull.
Have a look to this other plugin

http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html

scroll the page to middle, there is a multiple select example. Click on 
several options and watch the counter.

Considering that I submit a suggestion, do as you like. Presently the 
plugin works fine.

**Comment by thdoan** [comment]
Perhaps I'll add it as an option in the future. Thanks for the suggestion!

**Comment by badulesia** [comment]
Le 05/04/2017 à 04:09, Tom Doan a écrit :
> Perhaps I'll add it as an option in the future. Thanks for the suggestion!
>
Another possibility. I agree.
Thank you.

**Comment by badulesia** [comment]
Hello.
I wend down the script and modified it, in order to obtain what I suggested.

I have added a "verbose" property to oOptions. Default value is false.
- if set to false, the display is the list of selected as previously.
- if true is given by `$('.pretty').prettyDropdown({ verbose:true });`
and more than 2 options are selected, than a message displaying the number of selected options over the total is displayed. Notice that the title tooltip still displays the complete list of selected options.

I have modified the code between lines 444 to 453, I tried to use the same var naming convention that you used.
Launch the test demo attached: 2 options are already selected, just select another one and see the message displayed.

Can you consider adding this to the mainstream code ?
Thank you.
[test.zip](https://github.com/thdoan/pretty-dropdowns/files/903700/test.zip)

**Comment by thdoan** [comment]
Sure, can you submit a PR?

Since the threshold of 2 may work for you but not for others, one thing I will recommend is to change `verbose` from boolean to integer, where 0 means off and anything above 0 is the threshold to display number of selected.

**Comment by badulesia** [comment]
Here is a new test demo.
I set the default `verbose `to 0 (off). Others values (>0) means that the verbose display is active. It seems to me more logical to do so, rather than using -1.
I also add a check for the given value (line 28) not to be negative. Modified code is between lines 445 to 450.
[test.zip](https://github.com/thdoan/pretty-dropdowns/files/904783/test.zip)

**Comment by thdoan** [comment]
The reason I chose -1 and no 0 is because I have seen some clients who actually prefer to have the menu say "0 selected" instead of "--" or blank when nothing is selected. This way, they can accomplish this by setting verbose to 0.

**Comment by badulesia** [comment]
Le 07/04/2017 à 09:27, Tom Doan a écrit :
> The reason I chose -1 and no 0 is because I have seen some clients who
> actually prefer to have the menu say "0 selected" instead of "--" or
> blank when nothing is selected. This way, they can accomplish this by
> setting verbose to 0.
Ok, I change.

**Comment by badulesia** [comment]
New version attached
[test.zip](https://github.com/thdoan/pretty-dropdowns/files/904923/test.zip)

**Comment by thdoan** [comment]
Option `multiVerbosity` was added to v4.10.0.
