### ISSUE TITLE
None selected by default

### ISSUE THREAD

**Issue by revealitmedia** [thdoan/pretty-dropdowns#7]
When using a multi select, the first option is always selected by default.  If you click on that first option, it is unselected, and you see the placeholder "None selected".  Is there a way to not have any options selected by default?

**Comment by revealitmedia** [comment]
I was able to find a workaround.  Havent fully tested, but seems to do the trick:

if (jQuery().prettyDropdown) {
		$dropdown = $('#productlist').prettyDropdown({});
		$('#productlist').on('change', function() {
			if ($("#product-placeholder").length) {
				$("#product-placeholder").prop("selected", false).prop('disabled', 'disabled');
				$dropdown.refresh();
			}
		})
	}

**Comment by thdoan** [comment]
This issue has been fixed in [v4.11.0](https://github.com/thdoan/pretty-dropdowns/releases/tag/v4.11.0).
