### ISSUE TITLE
Full width Select

### ISSUE THREAD

**Issue by amichel86** [thdoan/pretty-dropdowns#9]
Thank you for your plugin!

Is there an option to have it 100% wide by default or we need to play around in the CSS?

**Comment by itsems** [comment]
+1 have same question here
thx for your plugin!

**Comment by thdoan** [comment]
Good suggestion -- I'll add a `width` option as well since the `height` option is getting lonely ;).

**Comment by amichel86** [comment]
For those wondering here's the basic CSS override for it to be 100% wide:

`.prettydropdown {
  display: block;
  width: 100%!important;
  
  > ul {
    width: 100%!important;
    
    li {
      width: 100%!important;
    }
    
  }
  
}`

**Comment by thdoan** [comment]
@amichel86 great, thanks. I currently don't have the bandwidth to add a `width` option that takes both px and % units, so maybe someone can tackle this and submit a PR. In the meantime, the quickest solution is to override the CSS as shown above.

**Comment by thdoan** [comment]
Note that there is now a `width` option beginning with v4.13.0.
